on:
  push:
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec --order=random
      - name: Build
        run: shards build